//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using Newtonsoft.Json;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class header {
    
    private string contentField;
    
    private System.DateTime createdField;
    
    private string copyrightField;
    
    private System.Nullable<System.DateTime> startField;
    
    private bool startFieldSpecified;
    
    private string periodField;
    
    /// <remarks/>
    public string content {
        get {
            return this.contentField;
        }
        set {
            this.contentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime created {
        get {
            return this.createdField;
        }
        set {
            this.createdField = value;
        }
    }
    
    /// <remarks/>
    public string copyright {
        get {
            return this.copyrightField;
        }
        set {
            this.copyrightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool startSpecified {
        get {
            return this.startFieldSpecified;
        }
        set {
            this.startFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="duration", IsNullable=true)]
    public string period {
        get {
            return this.periodField;
        }
        set {
            this.periodField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class assetType {
    
    private string uRIField;
    
    private assetTypeCaption captionField;
    
    private string providerField;
    
    private string creditLineField;
    
    private string typeField;
    
    private string widthField;
    
    private string heightField;
    
    private bool primaryField;
    
    private bool primaryFieldSpecified;
    
    private string categoryField;
    
    /// <remarks/>
    public string URI {
        get {
            return this.uRIField;
        }
        set {
            this.uRIField = value;
        }
    }
    
    /// <remarks/>
    public assetTypeCaption caption {
        get {
            return this.captionField;
        }
        set {
            this.captionField = value;
        }
    }
    
    /// <remarks/>
    public string provider {
        get {
            return this.providerField;
        }
        set {
            this.providerField = value;
        }
    }
    
    /// <remarks/>
    public string creditLine {
        get {
            return this.creditLineField;
        }
        set {
            this.creditLineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool primary {
        get {
            return this.primaryField;
        }
        set {
            this.primaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool primarySpecified {
        get {
            return this.primaryFieldSpecified;
        }
        set {
            this.primaryFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class assetTypeCaption {
    
    private string langField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ratingType {
    
    private ratingTypeAdvisory[] advisoriesField;
    
    private ratingTypeRating[] ratingField;
    
    private ratingTypeQualityRating qualityRatingField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("advisory", IsNullable=false)]
    public ratingTypeAdvisory[] advisories {
        get {
            return this.advisoriesField;
        }
        set {
            this.advisoriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("rating")]
    public ratingTypeRating[] rating {
        get {
            return this.ratingField;
        }
        set {
            this.ratingField = value;
        }
    }
    
    /// <remarks/>
    public ratingTypeQualityRating qualityRating {
        get {
            return this.qualityRatingField;
        }
        set {
            this.qualityRatingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ratingTypeAdvisory {
    
    private string ratingsBodyField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string ratingsBody {
        get {
            return this.ratingsBodyField;
        }
        set {
            this.ratingsBodyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ratingTypeRating {
    
    private string warningField;
    
    private string areaField;
    
    private string codeField;
    
    private string descriptionField;
    
    private string ratingsBodyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string warning {
        get {
            return this.warningField;
        }
        set {
            this.warningField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string area {
        get {
            return this.areaField;
        }
        set {
            this.areaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string ratingsBody {
        get {
            return this.ratingsBodyField;
        }
        set {
            this.ratingsBodyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ratingTypeQualityRating {
    
    private string ratingsBodyField;
    
    private float valueField;
    
    private string numVotesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string ratingsBody {
        get {
            return this.ratingsBodyField;
        }
        set {
            this.ratingsBodyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string numVotes {
        get {
            return this.numVotesField;
        }
        set {
            this.numVotesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class awardType {
    
    private awardTypeName nameField;
    
    private awardTypeCategory categoryField;
    
    private string yearField;
    
    private awardTypeRecipient recipientField;
    
    private bool wonField;
    
    private bool wonFieldSpecified;
    
    /// <remarks/>
    public awardTypeName name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public awardTypeCategory category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="gYear")]
    public string year {
        get {
            return this.yearField;
        }
        set {
            this.yearField = value;
        }
    }
    
    /// <remarks/>
    public awardTypeRecipient recipient {
        get {
            return this.recipientField;
        }
        set {
            this.recipientField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool won {
        get {
            return this.wonField;
        }
        set {
            this.wonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool wonSpecified {
        get {
            return this.wonFieldSpecified;
        }
        set {
            this.wonFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class awardTypeName {
    
    private string awardIdField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string awardId {
        get {
            return this.awardIdField;
        }
        set {
            this.awardIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class awardTypeCategory {
    
    private string awardCatIdField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string awardCatId {
        get {
            return this.awardCatIdField;
        }
        set {
            this.awardCatIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class awardTypeRecipient {
    
    private string nameIdField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string nameId {
        get {
            return this.nameIdField;
        }
        set {
            this.nameIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class pNameType {
    
    private string firstField;
    
    private string middleField;
    
    private string lastField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string first {
        get {
            return this.firstField;
        }
        set {
            this.firstField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string middle {
        get {
            return this.middleField;
        }
        set {
            this.middleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string last {
        get {
            return this.lastField;
        }
        set {
            this.lastField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class titleDescType {
    
    private string sizeField;
    
    private string typeField;
    
    private string langField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string size {
        get {
            return this.sizeField;
        }
        set {
            this.sizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class on {
    
    private header headerField;
    
    private programsProgram[] programsField;
    
    private decimal schemaVersionField;
    
    public on() {
        this.schemaVersionField = ((decimal)(2.0m));
    }
    
    /// <remarks/>
    public header header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("program", IsNullable=false)]
    public programsProgram[] programs {
        get {
            return this.programsField;
        }
        set {
            this.programsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal schemaVersion {
        get {
            return this.schemaVersionField;
        }
        set {
            this.schemaVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class programsProgram {
    
    private titleDescType[] titlesField;
    
    private titleDescType[] descriptionsField;
    
    private castTypeMember[] castField;
    
    private crewTypeMember[] crewField;
    
    private string runTimeField;
    
    private string progTypeField;
    
    private programsProgramHoliday holidayField;
    
    private string[] countriesField;
    
    private awardType[] awardsField;
    
    private programsProgramGenre[] genresField;
    
    private ratingType ratingsField;
    
    private System.DateTime origAirDateField;
    
    private bool origAirDateFieldSpecified;
    
    private string colorCodeField;
    
    private programsProgramMovieInfo movieInfoField;
    
    private programsProgramEpisodeInfo episodeInfoField;
    
    private programsProgramSportsInfo sportsInfoField;
    
    private assetType[] imagesField;
    
    private string animationField;
    
    private string origAudioLangField;
    
    private string[] keywordsField;
    
    private string sourceTypeField;
    
    private string tMSIdField;
    
    private string altFilmIdField;
    
    private string rootIdField;
    
    private string versionIdField;
    
    private string connectorIdField;
    
    private string seasonIdField;
    
    private string seriesIdField;

    [XmlIgnore, JsonIgnore]
    public MongoDB.Bson.ObjectId Id { get; set; }
    public bool ShouldSerializeId()
    {
        return false;
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("title", IsNullable=false)]
    public titleDescType[] titles {
        get {
            return this.titlesField;
        }
        set {
            this.titlesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("desc", IsNullable=false)]
    public titleDescType[] descriptions {
        get {
            return this.descriptionsField;
        }
        set {
            this.descriptionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("member", IsNullable=false)]
    public castTypeMember[] cast {
        get {
            return this.castField;
        }
        set {
            this.castField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("member", IsNullable=false)]
    public crewTypeMember[] crew {
        get {
            return this.crewField;
        }
        set {
            this.crewField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="duration")]
    public string runTime {
        get {
            return this.runTimeField;
        }
        set {
            this.runTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string progType {
        get {
            return this.progTypeField;
        }
        set {
            this.progTypeField = value;
        }
    }
    
    /// <remarks/>
    public programsProgramHoliday holiday {
        get {
            return this.holidayField;
        }
        set {
            this.holidayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("country", DataType="token", IsNullable=false)]
    public string[] countries {
        get {
            return this.countriesField;
        }
        set {
            this.countriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("award", IsNullable=false)]
    public awardType[] awards {
        get {
            return this.awardsField;
        }
        set {
            this.awardsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("genre", IsNullable=false)]
    public programsProgramGenre[] genres {
        get {
            return this.genresField;
        }
        set {
            this.genresField = value;
        }
    }
    
    /// <remarks/>
    public ratingType ratings {
        get {
            return this.ratingsField;
        }
        set {
            this.ratingsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime origAirDate {
        get {
            return this.origAirDateField;
        }
        set {
            this.origAirDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool origAirDateSpecified {
        get {
            return this.origAirDateFieldSpecified;
        }
        set {
            this.origAirDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string colorCode {
        get {
            return this.colorCodeField;
        }
        set {
            this.colorCodeField = value;
        }
    }
    
    /// <remarks/>
    public programsProgramMovieInfo movieInfo {
        get {
            return this.movieInfoField;
        }
        set {
            this.movieInfoField = value;
        }
    }
    
    /// <remarks/>
    public programsProgramEpisodeInfo episodeInfo {
        get {
            return this.episodeInfoField;
        }
        set {
            this.episodeInfoField = value;
        }
    }
    
    /// <remarks/>
    public programsProgramSportsInfo sportsInfo {
        get {
            return this.sportsInfoField;
        }
        set {
            this.sportsInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("image", IsNullable=false)]
    public assetType[] images {
        get {
            return this.imagesField;
        }
        set {
            this.imagesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string animation {
        get {
            return this.animationField;
        }
        set {
            this.animationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="language")]
    public string origAudioLang {
        get {
            return this.origAudioLangField;
        }
        set {
            this.origAudioLangField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("keyword", DataType="token", IsNullable=false)]
    public string[] keywords {
        get {
            return this.keywordsField;
        }
        set {
            this.keywordsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string sourceType {
        get {
            return this.sourceTypeField;
        }
        set {
            this.sourceTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string TMSId {
        get {
            return this.tMSIdField;
        }
        set {
            this.tMSIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string altFilmId {
        get {
            return this.altFilmIdField;
        }
        set {
            this.altFilmIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string rootId {
        get {
            return this.rootIdField;
        }
        set {
            this.rootIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string versionId {
        get {
            return this.versionIdField;
        }
        set {
            this.versionIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string connectorId {
        get {
            return this.connectorIdField;
        }
        set {
            this.connectorIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string seasonId {
        get {
            return this.seasonIdField;
        }
        set {
            this.seasonIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string seriesId {
        get {
            return this.seriesIdField;
        }
        set {
            this.seriesIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class castTypeMember {
    
    private string characterNameField;
    
    private string roleField;
    
    private castTypeMemberName nameField;
    
    private string personIdField;
    
    private string ordField;
    
    /// <remarks/>
    public string characterName {
        get {
            return this.characterNameField;
        }
        set {
            this.characterNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string role {
        get {
            return this.roleField;
        }
        set {
            this.roleField = value;
        }
    }
    
    /// <remarks/>
    public castTypeMemberName name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string personId {
        get {
            return this.personIdField;
        }
        set {
            this.personIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string ord {
        get {
            return this.ordField;
        }
        set {
            this.ordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class castTypeMemberName : pNameType {
    
    private string nameIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string nameId {
        get {
            return this.nameIdField;
        }
        set {
            this.nameIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class crewTypeMember {
    
    private string roleField;
    
    private crewTypeMemberName nameField;
    
    private string personIdField;
    
    private string ordField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string role {
        get {
            return this.roleField;
        }
        set {
            this.roleField = value;
        }
    }
    
    /// <remarks/>
    public crewTypeMemberName name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string personId {
        get {
            return this.personIdField;
        }
        set {
            this.personIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string ord {
        get {
            return this.ordField;
        }
        set {
            this.ordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class crewTypeMemberName : pNameType {
    
    private string nameIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string nameId {
        get {
            return this.nameIdField;
        }
        set {
            this.nameIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class programsProgramHoliday {
    
    private string holidayIdField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string holidayId {
        get {
            return this.holidayIdField;
        }
        set {
            this.holidayIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class programsProgramGenre {
    
    private string genreIdField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string genreId {
        get {
            return this.genreIdField;
        }
        set {
            this.genreIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class programsProgramMovieInfo {
    
    private programsProgramMovieInfoRelease[] releasesField;
    
    private string[] soundMixesField;
    
    private string[] pictureFormatsField;
    
    private string[] productionCompaniesField;
    
    private string officialURLField;
    
    private programsProgramMovieInfoTrailer[] trailersField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("release", IsNullable=false)]
    public programsProgramMovieInfoRelease[] releases {
        get {
            return this.releasesField;
        }
        set {
            this.releasesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("soundMix", DataType="token", IsNullable=false)]
    public string[] soundMixes {
        get {
            return this.soundMixesField;
        }
        set {
            this.soundMixesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("pictureFormat", DataType="token", IsNullable=false)]
    public string[] pictureFormats {
        get {
            return this.pictureFormatsField;
        }
        set {
            this.pictureFormatsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("name", DataType="token", IsNullable=false)]
    public string[] productionCompanies {
        get {
            return this.productionCompaniesField;
        }
        set {
            this.productionCompaniesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string officialURL {
        get {
            return this.officialURLField;
        }
        set {
            this.officialURLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("trailer", IsNullable=false)]
    public programsProgramMovieInfoTrailer[] trailers {
        get {
            return this.trailersField;
        }
        set {
            this.trailersField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class programsProgramMovieInfoRelease {
    
    private string locationField;
    
    private string[] distributorsField;
    
    private string countryField;
    
    private string typeField;
    
    private string dateField;
    
    /// <remarks/>
    public string location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("name", DataType="token", IsNullable=false)]
    public string[] distributors {
        get {
            return this.distributorsField;
        }
        set {
            this.distributorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class programsProgramMovieInfoTrailer {
    
    private string formatField;
    
    private string uRLField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string format {
        get {
            return this.formatField;
        }
        set {
            this.formatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string URL {
        get {
            return this.uRLField;
        }
        set {
            this.uRLField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class programsProgramEpisodeInfo {
    
    private titleDescType titleField;
    
    private string synNumField;
    
    private string altSynNumField;
    
    private string seasonField;
    
    private string numberField;
    
    private string episodesField;
    
    /// <remarks/>
    public titleDescType title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string synNum {
        get {
            return this.synNumField;
        }
        set {
            this.synNumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string altSynNum {
        get {
            return this.altSynNumField;
        }
        set {
            this.altSynNumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string season {
        get {
            return this.seasonField;
        }
        set {
            this.seasonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string episodes {
        get {
            return this.episodesField;
        }
        set {
            this.episodesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class programsProgramSportsInfo {
    
    private System.DateTime gameDateField;
    
    private System.DateTime gameTimeField;
    
    private bool gameTimeFieldSpecified;
    
    private string gameTimeZoneField;
    
    private programsProgramSportsInfoVenue venueField;
    
    private programsProgramSportsInfoTeam[] teamField;
    
    private programsProgramSportsInfoSeason seasonField;
    
    private programsProgramSportsInfoPlayoffRound playoffRoundField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime gameDate {
        get {
            return this.gameDateField;
        }
        set {
            this.gameDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime gameTime {
        get {
            return this.gameTimeField;
        }
        set {
            this.gameTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool gameTimeSpecified {
        get {
            return this.gameTimeFieldSpecified;
        }
        set {
            this.gameTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string gameTimeZone {
        get {
            return this.gameTimeZoneField;
        }
        set {
            this.gameTimeZoneField = value;
        }
    }
    
    /// <remarks/>
    public programsProgramSportsInfoVenue venue {
        get {
            return this.venueField;
        }
        set {
            this.venueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("team")]
    public programsProgramSportsInfoTeam[] team {
        get {
            return this.teamField;
        }
        set {
            this.teamField = value;
        }
    }
    
    /// <remarks/>
    public programsProgramSportsInfoSeason season {
        get {
            return this.seasonField;
        }
        set {
            this.seasonField = value;
        }
    }
    
    /// <remarks/>
    public programsProgramSportsInfoPlayoffRound playoffRound {
        get {
            return this.playoffRoundField;
        }
        set {
            this.playoffRoundField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class programsProgramSportsInfoVenue {
    
    private string venueBrandIdField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string venueBrandId {
        get {
            return this.venueBrandIdField;
        }
        set {
            this.venueBrandIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class programsProgramSportsInfoTeam {
    
    private string teamBrandIdField;
    
    private bool isHomeField;
    
    private bool isHomeFieldSpecified;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string teamBrandId {
        get {
            return this.teamBrandIdField;
        }
        set {
            this.teamBrandIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool isHome {
        get {
            return this.isHomeField;
        }
        set {
            this.isHomeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool isHomeSpecified {
        get {
            return this.isHomeFieldSpecified;
        }
        set {
            this.isHomeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class programsProgramSportsInfoSeason {
    
    private string typeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class programsProgramSportsInfoPlayoffRound {
    
    private string gameNumberField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string gameNumber {
        get {
            return this.gameNumberField;
        }
        set {
            this.gameNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class programs {
    
    private programsProgram[] programField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("program")]
    public programsProgram[] program {
        get {
            return this.programField;
        }
        set {
            this.programField = value;
        }
    }
}
